language: python
python:
- '2.7'
- '3.5'
- '3.6'
dist: trusty
services:
- docker
before_install:
- pip install codecov
- pip install pytest-cov
- pip install codacy-coverage
install:
- pip install .
- pip install -r requirements.txt
script:
- pylint  -E ddpaper/
#- mypy
- py.test ./ --cov=./
- PYTHONPATH=./ py.test ./ --cov=./
after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
- codecov
env:
  matrix:
    secure: r04X7Rtrajt/hLZ9wGjZ1og9D1QetMwIV3XWERJSFn4ae9eb2cWW1vtHwD+K7/o/QoXZP8u88Re0PId9I950q/gLMDcRfFvvhLrrThuF9ptJK2KtivzANz8j/sIQSxheOausctJFJf6H9SJi+VRzsdLXn5a5bfGQohJSl9NI+ivtVFbFXSwnclzBBpG7y2xzRY7yiaAnOAHvBtTNoXDaNZhhXp3IvIucfQhyJzn24UZ64TA4ZcVeIRZWecLaZhnNunEIQHAO00PYhNNPU1jNtUYPe8Jpry0VenNuW4HlyVWD1kIEGSJN/K3VvqQT0qEr5guHQzhTEuTK5BWFaTPDASwSW6GJ78PZus8vXLt1Hrrzk368Cad/C5aF+wkTs63qGu3qL/dUnBKYsBRKOOeoejv0MmoI0AT2BSSLAwscAzbLMkCfHznyURxy/1Ikq9P7Dg6U9LRPFD/Tky+QnkDwE5q0B/lptrQ/6lMcxZp+aIEiYh5Z9pmB/PCafrp9x0G8P1cdLiKhsg1twoKXKnoEhlb07mPJL/bZEKI9Vb+rebYmSVBzz+byf4PxyIIbwdoU/6s0JfRYioSNGC9kHWxxyaXcJzQH3cjw2SABQNlpVe8G/Pl4F5mY38EH3VFF0t1oeOEsKtc2IHj7QVZbj7IPbZT0F7xH3IUmss4pVcgh6AQ=
